name: OddTransport
main: info.somethingodd.bukkit.OddTransport.OddTransport
version: 0.1
website: http://bukkit.somethingodd.info
author: petteyg359
softdepend: [OddItem]
description: >
             Transportation
commands:
  oddtransport:
    usage: |
           /<command>
           Lists your transporters.
permissions:
  oddtransport:
    description: Gives access to all OddTransport commands
    children:
      oddtransport.clear: true
      oddtransport.create: true
      oddtransport.destroy: true
      oddtransport.list: true
      oddtransport.use: true
    oddtransport.clear:
      children:
        oddtransport.clear.own: true
      default: true
      description: Allows clearing of all transporters
    oddtransport.clear.own:
      default: op
      description: Allows clearing owned transporters
    oddtransport.create:
      default: op
      description: Allows creation of transporters
    oddtransport.destroy:
      children:
        oddtransport.destroy.own: true
      default: op
      description: Allows destruction of all transporters
    oddtransport.destroy.own:
      default: true
      description: Allows destruction of owned transporters
    oddtransport.use:
      children:
        oddtransport.use.own: true
      default: true
      description: Allows use of transporters
    oddtransport.use.own:
      default: true
      description: Allows use of owned transporters

