name: OddTransport
main: info.somethingodd.OddTransport.OddTransport
version: 0.2
website: http://bukkit.somethingodd.info
author: petteyg359
softdepend: [OddItem]
description: >
             Transportation
commands:
    oddtransport:
        usage: |
               /<command>
               Lists your transporters.
permissions:
    oddtransport:
        children:
            oddtransport.clear: false
            oddtransport.create: true
            oddtransport.destroy: false
            oddtransport.list: true
            oddtransport.use: true
        default: op
        description: Gives access to all OddTransport commands
    oddtransport.clear:
        default: op
        description: Allows clearing of all transporters
    oddtransport.create:
        default: op
        description: Allows creation of transporters
    oddtransport.destroy:
        default: op
        description: Allows destruction of all transporters
    oddtransport.list:
        default: true
        description: Allows listing of owned transporters.
    oddtransport.use:
        default: true
        description: Allows use of all transporters